package com.vag.lmsapp.util

class DbColumns {
    companion object {
        const val ACTIVITY_LOGS = "activity_logs"
        const val CLAIM_RECEIPT_PICTURES = "claim_receipt_pictures"
        const val CUSTOMERS = "customers"
        const val DELIVERY_PROFILES = "delivery_profiles"
        const val DISCOUNTS = "discounts"
        const val EXPENSES = "expenses"
        const val EXTRAS = "extras"
        const val INVENTORY_LOGS = "inventory_log"
        const val JOB_ORDERS = "job_orders"
        const val JOB_ORDER_DELIVERY_CHARGE = "job_order_delivery_charges"
        const val JOB_ORDER_DISCOUNT = "job_order_discounts"
        const val JOB_ORDER_EXTRAS = "job_order_extras"
        const val JOB_ORDER_PAYMENTS = "job_order_payments"
        const val JOB_ORDER_PICTURES = "job_order_pictures"
        const val JOB_ORDER_PRODUCTS = "job_order_products"
        const val JOB_ORDER_SERVICES = "job_order_services"
        const val JOB_ORDER_PACKAGES = "job_order_packages"
        const val MACHINES = "machines"
        const val MACHINE_REMARKS = "machine_remarks"
        const val MACHINE_USAGES = "machine_usages"
        const val PACKAGES = "packages"
        const val PACKAGE_EXTRAS = "package_extras"
        const val PACKAGE_PRODUCTS = "package_products"
        const val PACKAGE_SERVICES = "package_services"
        const val PRODUCTS = "products"
        const val SERVICES = "services"
        const val SHOP = "shops"
        const val USERS = "users"
        const val TEXT_MESSAGE_TEMPLATES = "text_message_templates"
    }
}